# -*- coding: utf-8 -*-
"""greating app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taPtPpxxj-HfujxHtq0Txo-inyADlhNo
"""

import streamlit as st
st.title("welcome to our first website using streamlit")
name=st.text_input("What is your name ?")
if name:
  st.write("welcome !",name)
  balloons()